### ISSUE TITLE
VP8enc: selkies-gstreamer fails with Missing gstreamer plugins:', ['vpx']

### ISSUE THREAD

**Issue by ch9hn** [selkies-project/docker-nvidia-glx-desktop#34]
Hello,
when I change the encoding codec from e.g. x264enc to vp8enc and restart the container (docker-compose down && docker-compose up -d) the selkies-gstreamer doesn't start up and fails with the following error:

```
INFO: gst-python install looks OK
Traceback (most recent call last):
  File "/usr/local/bin/selkies-gstreamer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/selkies_gstreamer/__main__.py", line 508, in main
    app = GSTWebRTCApp(stun_servers, turn_servers, enable_audio, curr_fps, args.encoder, curr_video_bitrate, curr_audio_bitrate)
  File "/usr/local/lib/python3.8/dist-packages/selkies_gstreamer/gstwebrtc_app.py", line 74, in __init__
    self.check_plugins()
  File "/usr/local/lib/python3.8/dist-packages/selkies_gstreamer/gstwebrtc_app.py", line 633, in check_plugins
    raise GSTWebRTCAppError('Missing gstreamer plugins:', missing)
gstwebrtc_app.GSTWebRTCAppError: ('Missing gstreamer plugins:', ['vpx'])
Waiting for X socket
X socket is ready
sed: couldn't open temporary file /opt/gst-web/sed0pNTVu: Permission denied
```

How its possible to get it to run ?

**Comment by ehfd** [comment]
Ahh, sorry. That's a development feature. Not available yet. I will close when it's available.

**Comment by ch9hn** [comment]
Thank you very much for the clarification :)

**Comment by ehfd** [comment]
It will be delivered at the same time to #32.

**Comment by ehfd** [comment]
Should be resolved.
